### ISSUE TITLE
Add MacOS-based gitignores so you stop commiting .DS_Store files

### ISSUE THREAD

**Issue by chipbuster** [El-minadero/Sean-Bot#8]
https://www.gitignore.io/api/macos

**Comment by chipbuster** [comment]
Prooooooobably a duplicate of #1

**Comment by El-minadero** [comment]
I DO THAT. But for some reason they keep coming back :'(

**Comment by chipbuster** [comment]
The .gitignore present on GitHub very definitely does *not* have a rule for Apple files

**Comment by El-minadero** [comment]
"Apple Files"?

**Comment by chipbuster** [comment]
https://www.gitignore.io/api/macos

**Comment by El-minadero** [comment]
Ok, issue possibly resolved in commit: 7288be8c8ee0d6ec8a02f8f5d79c473b668b4ad9 (How do i properly document this?)
